wandb_version: 1

learning_rate:
  desc: null
  value: 0.00011654896927748646
architecture:
  desc: null
  value: DCNN
dataset:
  desc: null
  value: CIFAR-10
epochs:
  desc: null
  value: 7
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1686917673.809311
    t:
      1:
      - 1
      - 4
      - 5
      - 35
      - 41
      - 53
      - 55
      2:
      - 1
      - 4
      - 5
      - 35
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 19
      - 23
      4: 3.10.8
      5: 0.15.4
      8:
      - 1
      - 3
      - 5
